export const CREATING_TASK_SUCCESS = 'CREATING_TASK_SUCCESS'
export const FETCHING_TASKS = 'FETCHING_TASKS'
export const FETCHING_TASKS_SUCCESS = 'FETCHING_TASKS_SUCCESS'
export const FETCHING_TASKS_ERROR = 'FETCHING_TASKS_ERROR'

